import { library } from '@fortawesome/fontawesome-svg-core';
import { faFloppyDisk } from '@fortawesome/free-regular-svg-icons';


import { 
    faDiamondTurnRight, 
    faEllipsisVertical,
    faCrosshairs,
    faXmark,
    faTrashCan,
    faQuestionCircle,
    faExternalLinkAlt,
    faMedal,
    faEye,
    faPlus,
    faBars,
    faLink,
    faCopy, 
    faSpinner,
    faList,faExpandAlt, faHouseChimney,
    faPaperclip, faRotateLeft, faUserPlus,
    faSearch,
    faMagnifyingGlass,
    faSquareShareNodes,
    faWindowMinimize,
    faShare,
    faDownLeftAndUpRightToCenter,
    faPenToSquare, 
    faCaretDown,
    faCaretUp
} from '@fortawesome/free-solid-svg-icons';


library.add(faDiamondTurnRight, 
    faEllipsisVertical,
    faCrosshairs,
    faXmark,
    faTrashCan,
    faQuestionCircle,
    faExternalLinkAlt,
    faMedal,
    faEye,
    faPlus,
    faBars,
    faLink,
    faCopy, 
    faSpinner,
    faList,faExpandAlt, faHouseChimney,
    faPaperclip, faRotateLeft, faUserPlus,
    faSearch,
    faMagnifyingGlass,
    faFloppyDisk,
    faSquareShareNodes,
    faWindowMinimize,
    faShare,faDownLeftAndUpRightToCenter,
    faPenToSquare, faCaretDown, faCaretUp);
